### ISSUE TITLE
Arbitrary stream randomly ends at the middle of the track

### ISSUE THREAD

**Issue by skick1234** [discordjs/voice#141] opened 2021-06-27 03:11 UTC
**Please describe the problem you are having in as much detail as possible:**

Arbitrary stream randomly ends at the middle of the track. I cannot reproduce it but sometimes it happened with the same URL.
I check the URL after the stream ended. It is still downloadable and plays the full track after downloading on my PC.

**Further details:**

- @discordjs/voice version: 0.5.0
- Node.js version: 14.17.0
- Operating system: Windows 10 / Ubuntu 20.04.2 LTS 
- Priority this issue should have – please be realistic and elaborate if possible: normal

**Comment by Snowflake107** [comment] 2021-06-27 03:43
might be related to #124

**Comment by amishshah** [comment] 2021-06-27 07:45
Can you share your code? And also whether or not any errors are emitted from the player

**Comment by skick1234** [comment] 2021-06-27 08:15
> Can you share your code?
And also whether or not any errors are emitted from the player

The stream stop and `AudioPlayer` change the state to Idle. Error event is not emitted.

I don't think it is due to my code

```
<AudioPlayer>.play(createAudioResource("stream url", {
  inputType: StreamType.Arbitrary,
  inlineVolume: true,
})).on("stateChange", (oldState, newState) => {
  if (newState.status === AudioPlayerStatus.Idle && oldState.status !== AudioPlayerStatus.Idle) {
    // Finish song
  }
}).on("error", console.error);
```

It randomly happens, not every time play.

**Comment by amishshah** [comment] 2021-06-27 08:27
Can you see if the suggestions in this thread fix your issue:

https://github.com/discordjs/voice/issues/117

**Comment by skick1234** [comment] 2021-06-27 08:32
> Can you see if the suggestions in this thread fix your issue:
> 
> https://github.com/discordjs/voice/issues/117

I created this issue because of arbitrary stream .-. So it is not recommended to use this?

**Comment by amishshah** [comment] 2021-06-27 08:35
I think your issue is due to using FFmpeg, by default we don't provide any reconnect parameters since that would be opinionated.

I am looking into a way to make this easier to customise, but for now, you'd have to create your own FFmpeg with reconnect parameters as shown in the issue above (your issue has the same symptoms as the issue above, so I'm assuming it's due to that)

**Comment by skick1234** [comment] 2021-06-27 09:02
> I think your issue is due to using FFmpeg, by default we don't provide any reconnect parameters since that would be opinionated.

Yes, my bot uses raw stream with reconnect params doesn't have that problem.

> I am looking into a way to make this easier to customise, but for now, you'd have to create your own FFmpeg with reconnect parameters as shown in the issue above (your issue has the same symptoms as the issue above, so I'm assuming it's due to that)

Sounds promising, should I open the issue till you solve this?

**Comment by amishshah** [comment] 2021-06-27 09:20
Sure, opening an issue would be useful 👍

**Comment by skick1234** [comment] 2021-06-27 09:23
I mean open this issue :v anyway, hope you find out a good solution soon. I have no idea :>

**Comment by amishshah** [comment] 2021-06-27 20:47
Closing this issue since it seems to be resolved using the above steps, and is a duplicate of https://github.com/discordjs/voice/issues/117.

Will track the overall issue in a new separate issue.

**Closed by amishshah** 2021-06-27 20:47 UTC
Labels: bug
